### ISSUE TITLE
Add participant name to the URL

### ISSUE THREAD

**Issue by brittneygallagher** [AIObjectives/talk-to-the-city-reports#60]
**Repro steps**

1. Go to https://tttc-turbo.web.app/report/heal-michigan-7-adjusted-backup-final (not as the owner)
2. Click the pipe icon in the bottom right.
3. Scroll down to "Participant filter"
4. Type "Holly Wilson"
5. Click Generate Report

**Expected behavior**
The report output, both the circles and the text is filtered to only include Holly Wilson
A unique URL is generated "https://tttc-turbo.web.app/report/heal-michigan-7-adjusted-backup-final-holly-wilson"

**Actual behavior**
The report output, both the circles and the text is filtered to only include Holly Wilson
The URL remains unchanged

**Additional context**
It's confusing to show all these features to inexperienced users. Having a unique URL per participant will significantly decrease the confusion for participants getting to the information they need to validate.

**Comment by colleenm** [comment]
Can we add the name as a URL parameter instead of of part of the base URL? like "https://tttc-turbo.web.app/report/heal-michigan-7-adjusted-backup-final?name=holly-wilson" (either hyphen or underscore as the delimiter is fine)

This is more extensible, in case we want to add more URL params in the future

**Comment by lightningorb** [comment]
Done.
